name: Release

on:
  push:
    tags:
      - 'v*.*.*'    # Matches v1.7.3
      - '*.*.*'      # Matches 1.7.3
      - 'v*.*'       # Matches v2.3
      - '*.*'        # Matches 2.3

permissions:
  contents: write

jobs:
  quality-checks:
    uses: ./.github/workflows/checks.yml

  release:
    needs: quality-checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Verify tag matches plugin version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        PLUGIN_VERSION=$(grep -oP 'Version:\s*\K[\d.]+' umami-tracking/umami-tracking.php)
        
        echo "Tag version: $TAG_VERSION"
        echo "Plugin version: $PLUGIN_VERSION"
        
        if [ "$TAG_VERSION" != "$PLUGIN_VERSION" ]; then
          echo "Tag version does not match plugin version!"
          exit 1
        fi

    - name: Install WP-CLI dist-archive command
      run: wp package install wp-cli/dist-archive-command

    - name: Build plugin zip
      run: |
        wp dist-archive ./umami-tracking --format=zip
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: umami-tracking.zip
        body: |
          Release of Umami Tracking v${{ github.ref_name }}
          
          ## Installation
          1. Download `umami-tracking.zip` from the assets below
          2. In WordPress admin, go to Plugins > Add New > Upload Plugin
          3. Choose the downloaded zip file and click Install Now
          4. Activate the plugin
          5. Configure your Website ID in Settings > Umami Tracking
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
